// flow-typed signature: f3544e5b0a90fd0207278209d11cbb01
// flow-typed version: <<STUB>>/grumbler-scripts_v^3.0.96/flow_v0.155.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grumbler-scripts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'grumbler-scripts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grumbler-scripts/config/constants' {
  declare module.exports: any;
}

declare module 'grumbler-scripts/config/karma.conf' {
  declare module.exports: any;
}

declare module 'grumbler-scripts/config/types' {
  declare module.exports: any;
}

declare module 'grumbler-scripts/config/webpack.config' {
  declare module.exports: any;
}

declare module 'grumbler-scripts/declarations' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grumbler-scripts/config/constants.js' {
  declare module.exports: $Exports<'grumbler-scripts/config/constants'>;
}
declare module 'grumbler-scripts/config/karma.conf.js' {
  declare module.exports: $Exports<'grumbler-scripts/config/karma.conf'>;
}
declare module 'grumbler-scripts/config/types.js' {
  declare module.exports: $Exports<'grumbler-scripts/config/types'>;
}
declare module 'grumbler-scripts/config/webpack.config.js' {
  declare module.exports: $Exports<'grumbler-scripts/config/webpack.config'>;
}
declare module 'grumbler-scripts/declarations.js' {
  declare module.exports: $Exports<'grumbler-scripts/declarations'>;
}
